
name: "npm test"
description: "Npm test"    
inputs:

  microservice_name:
    description: "Put microservice which you want test"
    required: true

  env_name:
    description: "Put test ENV name"
    required: true

runs:
  using: "composite"
  steps:

    - id: install_node
      uses: actions/setup-node@v1
      with:
        node-version: 17
      
    - id: npm_test
      shell: bash
      run: npm install && npm run test:${{ inputs.env_name }} ${{ inputs.microservice_name }}

