name: "npm test"
    description: "Npm test"    
    inputs:

      Microservice_name:
        description: "Put microservice which you want test"
        required: true

      ENV_Name:
        description: "Put test ENV name"
        required: true


    runs:
      using: "composite"
      steps:

        uses: actions/setup-node@v1
        with:
          node-version: 17

      - run: npm install && npm run test:${{ inputs.ENV_Name }} ${{ inputs.Microservice_name }}

