name: "npm test"
    description: "Npm test"
    
    inputs:

      Microservice_name:
        description: "Put microservice which you want test"
        required: true

      ENV_Name:
        description: "Put test ENV name"
        required: true


    runs:
      using: "composite"
      steps:

      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      # Install dependencies
      - run: npm install

      # Run tests
      - name: test
        run: npm run test:${{ inputs.ENV_Name }} ${{ inputs.Microservice_name }}

